### ISSUE TITLE
Jessica Parsons: Images or Single-page CMS

### ISSUE THREAD

**Issue by verythorough** [sacjs/sacjs.github.io#103]
I actually have two possible talks. I can submit them as separate issues if you prefer. I'm also happy to take feedback or questions.

Name: Jessica Parsons
Twitter Handle: @verythorough
GitHub Username: @verythorough
Employer: Netlify
(I live in the bay area now, but Sac is my hometown. 😄  )

---

Title: The Smart Shiba's Guide to Images for the Web
Talk length: 25min
Brief Description: Images take up roughly 60% of average page weight, making them a huge target for performance improvements. I'll go over several aspects of improving image loading, from choosing the right file type (including some new type on the horizon), to writing markup for responsive image loading, to making sure your images are cached properly. All concepts will be demonstrated with images of my pet shibas, Monty and Petunia. 😃 

This talk has not been recorded. I've given variations of it at a few meetups (Waffle JS, Google Developer Group, JAMstack SF), and received good feedback.

---

Title: Post-Monolithic Content Management
Talk length: 35min
Brief Description:  Static site generators have offered exciting new options for web developers, but until recently, they lacked a user-friendly interface for content editing—what many would call a CMS. There's now a handful of viable solutions out there, and as they gain traction, it's leading to some interesting confusion about what a CMS means when the architecture isn't all in one giant server app. I’ll present some different approaches to the problem, including Netlify CMS, an open-source, Git-based approach that's built with React.

I presented a version of this at SFHTML5 in May: https://youtu.be/UgHSqXeoOiY

**Comment by dlindahl** [comment]
Thanks for the submission @verythorough! I really like the abstract for the Images talk, let's go with that one. And no, its not _entirely_ because we'll get to see pics of Shibas 😀 🐕  Also, heads up, we are recording our presentations so you'll be wearing a wireless mic pack.

Do you have any questions for us! Our website is at sacjs.com and our Meetup.com page is https://www.meetup.com/The-Sacramento-Javascript-Meetup/ which should answer most of your questions, but don't hesitate to ask! Really looking forward to having you back home!

**Comment by verythorough** [comment]
Thanks! I love this talk! 😺 I think I've got all the info I need. Looking forward to Tuesday!
